// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:news_c17/data/model/sources_response/Source.dart';
import 'package:news_c17/data/model/sources_response/Sources_response.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SourceAdapter());
    registerAdapter(SourcesResponseAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SourceAdapter());
    registerAdapter(SourcesResponseAdapter());
  }
}
